### PR TITLE
Enabling module

### PR DESCRIPTION
**Pull request by arkdan**

### CODE REVIEW

**Comment by clobber** [comment]
Looks good, but just one nitpick though - at line 68 in OEXPCCAgentConfiguration.m https://github.com/OpenEmu/OpenEmuXPCCommunicator/pull/3/commits/53156c46169fdfa43b505ea679f49eff3cc1343f#diff-24525ce5b5c92589954f45825d0adc43R68

it should be `[[self class] OEXPCC_agentsApplicationSupportFolderPath]`
instead of `[OEXPCCAgentConfiguration OEXPCC_agentsApplicationSupportFolderPath]`

If you want to update that I will merge. Thank you!

**Comment by arkdan** [comment]
sure, changed. Because i already merged branched, i had to make another pull request. Please check it out. Closing this one.

**Comment by arkdan** [comment]
..let me take this chance to ask you a question:

what is the reason behind OEXPCCAgentConfiguration should be used only from the main application? (reading your comment)

The issue is, execution of the app blocks under XCTests bundle. Which is a bummer. To be honest i didn't dig far enough to understand the reason. I'd appreciate it if you could comment on that. I'm hoping it's somehow possible to overcome this constraint.

Thanks.

**Comment by PsychoH13** [comment]
That's because the main application is the one that can run the process and tell it what process identifier to listen to. Since you can launch multiple processes you need a way to know which one you need to send a specific NSXPCListenerEndpoint to.

**Pull request closed without merging**
